In [1]:
import torch

In [2]:
x = torch.tensor(2.0, requires_grad=True)

In [3]:
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1

In [4]:
y

tensor(63., grad_fn=<AddBackward0>)

In [5]:
y.backward()

In [6]:
x.grad

tensor(93.)

In [7]:
a = torch.tensor([[1., 2., 3.], [3., 2., 1.]], requires_grad=True)

In [8]:
a

tensor([[1., 2., 3.],
        [3., 2., 1.]], requires_grad=True)

In [12]:
b = 3*a + 2

In [13]:
print(b)

tensor([[ 5.,  8., 11.],
        [11.,  8.,  5.]], grad_fn=<AddBackward0>)


In [14]:
c = 2*b**2

In [15]:
print(c)

tensor([[ 50., 128., 242.],
        [242., 128.,  50.]], grad_fn=<MulBackward0>)


In [16]:
out = c.mean()

In [17]:
print(out)

tensor(140., grad_fn=<MeanBackward0>)


In [18]:
out.backward()

In [20]:
print(a.grad)

tensor([[10., 16., 22.],
        [22., 16., 10.]])
