In [1]:
import torch 
import numpy as np

In [3]:
x = torch.arange(6).reshape(3, 2)

In [4]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

### Indexing

In [6]:
x[1,1] 

tensor(3)

### Slicing

In [7]:
x[:, 1]

tensor([1, 3, 5])

In [8]:
x[:, 1:]

tensor([[1],
        [3],
        [5]])

### View vs Reshape

In [9]:
x = torch.arange(10)

In [10]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
x = x.reshape(2,5)

In [16]:
x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
x = torch.arange(10)

In [18]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
x.shape

torch.Size([10])

In [21]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
z = x.view(2,5)

In [23]:
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

### View works with data real time so making changes to the original tensor will change the updated one too

In [24]:
x[0] = 99

In [25]:
x

tensor([99,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [26]:
z

tensor([[99,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])

In [27]:
y = torch.arange(10)

In [28]:
y 

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
y.view(2, -1) ## Using -1 torch will try to infer what the 2nd dimension should be

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

## Tensor Arithmetic

In [30]:
a = torch.tensor([1., 2., 3.])
b = torch.tensor([4., 5., 6.])

In [32]:
a + b 

tensor([5., 7., 9.])

In [33]:
torch.add(a, b)

tensor([5., 7., 9.])

In [34]:
a.mul(b)

tensor([ 4., 10., 18.])

In [35]:
a.mul_(b)

tensor([ 4., 10., 18.])

In [36]:
a

tensor([ 4., 10., 18.])

In [37]:
a = torch.tensor([1., 2., 3.])

In [38]:
a

tensor([1., 2., 3.])

In [39]:
b

tensor([4., 5., 6.])

In [40]:
a * b

tensor([ 4., 10., 18.])

In [41]:
a.dot(b)

tensor(32.)

In [42]:
a = torch.tensor([[0, 2, 4], [1, 3, 5]])

In [43]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [44]:
b = torch.tensor([[6, 7], [8, 9], [10, 11]])

In [45]:
b

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [46]:
a.shape

torch.Size([2, 3])

In [47]:
b.shape

torch.Size([3, 2])

In [48]:
torch.mm(a,b)

tensor([[56, 62],
        [80, 89]])

In [49]:
a @ b

tensor([[56, 62],
        [80, 89]])

In [50]:
x = torch.tensor([2., 3., 4., 5.])

In [51]:
x.norm() ## Performs Euclidean Norm

tensor(7.3485)