In [1]:
import torch
import numpy as np

In [2]:
torch.__version__

'1.7.1+cu110'

In [3]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [4]:
type(arr)

numpy.ndarray

<img src="https://cdn-images-1.medium.com/max/2000/1*_D5ZvufDS38WkhK9rK32hQ.jpeg">

### Conversion of Numpy Array to Torch Tensor

#### Downside is that: Numpy array and the torch tensor have a direct connection
#### modifying the array will also makes changes to the tensor.

In [6]:
x = torch.from_numpy(arr)

In [7]:
type(x)

torch.Tensor

In [8]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [9]:
x.dtype

torch.int32

In [10]:
arr_2d = np.arange(0.0, 12.0)
arr_2d = arr_2d.reshape(4,3)

In [11]:
arr_2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [12]:
x2 = torch.from_numpy(arr_2d)

In [13]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [14]:
arr[0] = 99

In [15]:
arr

array([99,  2,  3,  4,  5])

In [16]:
x

tensor([99,  2,  3,  4,  5], dtype=torch.int32)

In [17]:
new_arr = np.arange(0, 10)
new_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
my_tensor = torch.tensor(new_arr)

In [19]:
my_new_tensor = torch.from_numpy(new_arr)

In [21]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [22]:
my_new_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [23]:
new_arr[0] = 99

In [24]:
my_new_tensor

tensor([99,  1,  2,  3,  4,  5,  6,  7,  8,  9], dtype=torch.int32)

In [25]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [26]:
arr_2 = np.array([1,2,3])

In [28]:
arr_2.dtype

dtype('int32')

In [29]:
torch.tensor(arr_2)

tensor([1, 2, 3], dtype=torch.int32)

In [31]:
y = torch.Tensor(arr_2)

In [33]:
y.dtype

torch.float32

## Creating Tensors from Scartch

In [34]:
torch.empty(2,2)

tensor([[5.9694e-39, 1.1571e-38],
        [8.4489e-39, 1.0286e-38]])

In [35]:
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [36]:
torch.zeros(2,3,dtype=torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [37]:
torch.ones(4,2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [38]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [39]:
torch.linspace(0, 16, 12).reshape(3,4)

tensor([[ 0.0000,  1.4545,  2.9091,  4.3636],
        [ 5.8182,  7.2727,  8.7273, 10.1818],
        [11.6364, 13.0909, 14.5455, 16.0000]])

In [40]:
my_tensor = torch.tensor([1, 2, 3])

In [41]:
my_tensor.dtype

torch.int64

In [42]:
my_tensor = my_tensor.type(torch.int32)

In [43]:
my_tensor.dtype

torch.int32

In [44]:
torch.rand(4,3) ## Uniform Distribution

tensor([[0.7860, 0.5145, 0.8177],
        [0.3532, 0.6469, 0.7277],
        [0.7415, 0.0163, 0.8330],
        [0.8710, 0.1186, 0.0085]])

In [45]:
torch.randn(4,3) ## Standard Normal Distribution

tensor([[ 1.1421,  0.0539, -1.1226],
        [ 0.2734,  0.9807, -1.8037],
        [ 0.9639, -0.6336,  0.6578],
        [-1.3794,  0.6451,  0.7780]])

In [46]:
torch.randint(low=0, high=10, size=(5,5)) ## 10 is exclusive

tensor([[7, 8, 1, 6, 6],
        [6, 2, 1, 9, 6],
        [4, 5, 4, 5, 0],
        [5, 8, 9, 6, 6],
        [8, 5, 5, 3, 7]])

In [47]:
x = torch.zeros(2, 5)

In [48]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [49]:
torch.rand_like(x)

tensor([[0.5946, 0.8716, 0.7158, 0.9135, 0.8849],
        [0.5092, 0.1892, 0.7563, 0.2268, 0.6112]])

In [50]:
torch.randn_like(x)

tensor([[ 0.5131, -0.2318,  0.9029,  0.4447, -1.0295],
        [ 0.7241, -0.8040, -0.8807, -0.7903,  0.0068]])

In [51]:
torch.randint_like(x, low=0, high=10)

tensor([[2., 0., 5., 3., 6.],
        [3., 2., 2., 7., 3.]])

In [52]:
torch.manual_seed(42)

In [53]:
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [54]:
torch.rand(2,3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [55]:
torch.rand(2,3)

tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])